spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      # create: 기존테이블 삭제 후 다시 생성 (DROP + CREATE)
      # create-drop: create와 같으나 종료시점에 테이블 DROP
      # update: 변경분만 반영(운영DB에서는 사용하면 안됨)
      # validate: 엔티티와 테이블이 정상 매핑되었는지만 확인
      # none: 사용하지 않음(사실상 없는 값이지만 관례상 none이라고 한다.)

      # 개발 초기 ( 운영 장비에서는 절대 사용 X ) : create, create-drop, update
      # 테스트 서버 : update, validate
      # 운영 : validate, none
    properties:
      hibernate:
        # System.out에 출력하는것 밑에 log는 log로 찍는것
        # 운영환경에서는 log로 찍어야 한다
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8081



